title: Q-POP-FerroDyn
description: Exascale Phase-field Solvers for Coupled Charge-elasticity-photon dynamics
theme: just-the-docs

url: https://DOE-COMMS.github.io/Q-POP-FerroDyn

aux_links:
  Template Repository: https://github.com/DOE-COMMS/Q-POP-FerroDyn
